In [1]:
import numpy as np


In [2]:
np.zeros(5)#Return a new array of given shape and type, filled with zeros.

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones(5)#Return a new array of given shape and type, filled with ones.


array([1., 1., 1., 1., 1.])

In [10]:
one=np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
one.ndim

2

In [12]:
# 3 dimensional arrays
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr=np.zeros((1,3,4))
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [17]:
arr.ndim

3

In [19]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
a=arr+5
a

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [24]:
a*2

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [25]:
a-1

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [27]:
np.eye(5)#Return a 2-D array with ones on the diagonal and zeros elsewhere.


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.empty((3,4))#Return a new array of given shape and type, without initializing entries.
#It means entries in the array can be anything random values

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [42]:
# Random module
import random
random.choice((1,2,3,4))#Choose a random element from a non-empty sequence.

1

In [34]:
random.choice("Ajay")

'y'

In [35]:
random.randrange(1,10)

6

In [36]:
random.random()#a random no generated between 0(included) and 1(excluded)


0.5482512622240768

In [37]:
lis=[1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [39]:
random.shuffle(lis)
lis

[3, 4, 5, 1, 2]

In [45]:
random.uniform(7,1)

5.754252726105987

In [2]:
# random numbers related concept in numpy
import numpy as np
np.array([])

array([], dtype=float64)

In [3]:
np.random.random_sample()

0.41048750121973276

In [4]:
# if you want random numbers in form of array (1 dimension)

np.random.random_sample((5,))

array([0.04210996, 0.49968271, 0.26032793, 0.64269749, 0.8504358 ])

In [5]:
np.random.rand(1)

array([0.6142493])

In [6]:
np.random.rand(2,3)

array([[0.9421095 , 0.11041231, 0.69109153],
       [0.2973191 , 0.69982145, 0.54800896]])

In [7]:
np.random.randn(2,3)#Return a sample (or samples) from the "standard normal" distribution

array([[-1.28666118, -0.94728349, -0.00567174],
       [ 0.38202975, -0.00858782, -1.57048905]])

In [35]:
np.random.randint(1,14,size=(3,3))# start from 1 and end at 10-1 and give array of shape 3,3

array([[ 3,  3, 11],
       [ 6,  6,  8],
       [ 3,  1, 10]], dtype=int32)

In [36]:
arr=np.random.randint(1,10,size=(3,3))
arr.ndim


2

In [37]:
arr.size

9

In [38]:
arr.shape

(3, 3)

In [49]:
# Re-shaping of array
import random
newarr=np.random.randint(1,10,size=(4,3))
newarr

array([[9, 3, 8],
       [6, 9, 8],
       [9, 9, 2],
       [6, 1, 9]], dtype=int32)

In [50]:
newarr.size

12

In [52]:
#using reshape 
newarr.reshape(2,6)#Returns an array containing the same data with a new shape.

array([[9, 3, 8, 6, 9, 8],
       [9, 9, 2, 6, 1, 9]], dtype=int32)

In [54]:
# Array size will never change,always reshape parameter should be multiple of original array
newarr.reshape(3,3)
# show an error because the original array size is 12

ValueError: cannot reshape array of size 12 into shape (3,3)

In [56]:
# In case you dont know coloums  in reshape what should be the row or coloumn count 
# use any -ve value for rows or coloums
newarr.reshape(4,-5)

array([[9, 3, 8],
       [6, 9, 8],
       [9, 9, 2],
       [6, 1, 9]], dtype=int32)

In [59]:
#same for rows
newarr.reshape(-1,4)

array([[9, 3, 8, 6],
       [9, 8, 9, 9],
       [2, 6, 1, 9]], dtype=int32)

In [61]:
newarr.reshape(4,3).base# to see the original array

array([[9, 3, 8],
       [6, 9, 8],
       [9, 9, 2],
       [6, 1, 9]], dtype=int32)

In [64]:
#3d
newarr.reshape(2,3,2)  #multiplication should be equal to arr size

array([[[9, 3],
        [8, 6],
        [9, 8]],

       [[9, 9],
        [2, 6],
        [1, 9]]], dtype=int32)

In [66]:
#4d
newarr.reshape(3,2,2,1)

array([[[[9],
         [3]],

        [[8],
         [6]]],


       [[[9],
         [8]],

        [[9],
         [9]]],


       [[[2],
         [6]],

        [[1],
         [9]]]], dtype=int32)

In [67]:
newarr.reshape(3,2,2,1).ndim

4

In [68]:
newarr.reshape(4,3,1)# 3 rows 1 coloumn repeated 4 times in 3-dimensiion

array([[[9],
        [3],
        [8]],

       [[6],
        [9],
        [8]],

       [[9],
        [9],
        [2]],

       [[6],
        [1],
        [9]]], dtype=int32)

In [70]:
# Conditions on array
arr=np.random.randint(1,10,(5,6))
arr

array([[7, 5, 4, 9, 8, 8],
       [7, 5, 7, 2, 2, 9],
       [1, 7, 8, 6, 9, 1],
       [1, 3, 1, 7, 6, 3],
       [9, 7, 6, 8, 1, 5]], dtype=int32)

In [71]:
arr.shape

(5, 6)

In [72]:
arr.size

30

In [73]:
arr.ndim

2

In [74]:
arr>3

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False,  True],
       [False,  True,  True,  True,  True, False],
       [False, False, False,  True,  True, False],
       [ True,  True,  True,  True, False,  True]])

In [75]:
arr[arr>3]

array([7, 5, 4, 9, 8, 8, 7, 5, 7, 9, 7, 8, 6, 9, 7, 6, 9, 7, 6, 8, 5],
      dtype=int32)

In [76]:
arr[arr<3]

array([2, 2, 1, 1, 1, 1, 1], dtype=int32)

In [79]:
# To access elements in an array
arr[0]

array([7, 5, 4, 9, 8, 8], dtype=int32)

In [80]:
arr[0][3]

np.int32(9)

In [81]:
# TO access 0th row to 2nd row
arr[0:2]

array([[7, 5, 4, 9, 8, 8],
       [7, 5, 7, 2, 2, 9]], dtype=int32)

In [83]:
# i want 0,1,2 row and 0,2 coloums
arr[0:3,[0,2]]

array([[7, 4],
       [7, 7],
       [1, 8]], dtype=int32)

In [84]:
# slicing bhot rows and colums together
arr

array([[7, 5, 4, 9, 8, 8],
       [7, 5, 7, 2, 2, 9],
       [1, 7, 8, 6, 9, 1],
       [1, 3, 1, 7, 6, 3],
       [9, 7, 6, 8, 1, 5]], dtype=int32)

In [89]:
#if i want to acces 0,1,2 row and 1,2,3 coloums

arr[0:3,1:4]

array([[5, 4, 9],
       [5, 7, 2],
       [7, 8, 6]], dtype=int32)

In [90]:
# mathematical operations on two arrays
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [91]:
arr1

array([[2, 1, 2],
       [2, 1, 2],
       [1, 1, 2]], dtype=int32)

In [92]:
arr2

array([[1, 1, 2],
       [1, 2, 2],
       [2, 2, 2]], dtype=int32)

In [93]:
arr1+arr2 # index wise element addition

array([[3, 2, 4],
       [3, 3, 4],
       [3, 3, 4]], dtype=int32)

In [94]:
arr1-arr2

array([[ 1,  0,  0],
       [ 1, -1,  0],
       [-1, -1,  0]], dtype=int32)

In [95]:
arr1*arr2#This is index multiplication not matrix multiplication

array([[2, 1, 4],
       [2, 2, 4],
       [2, 2, 4]], dtype=int32)

In [96]:
arr1/arr2

array([[2. , 1. , 1. ],
       [2. , 0.5, 1. ],
       [0.5, 0.5, 1. ]])

In [97]:
# Matrix multiplication
# matrix multiplication is dfferent from index wise multiplication
arr1 @ arr2

array([[ 7,  8, 10],
       [ 7,  8, 10],
       [ 6,  7,  8]], dtype=int32)

In [98]:
# Another way of matrix multiplication
np.dot(arr1,arr2)

array([[ 7,  8, 10],
       [ 7,  8, 10],
       [ 6,  7,  8]], dtype=int32)

In [103]:
# Transpose >> Converting rows to colums and colums to rows
arr

array([[7, 5, 4, 9, 8, 8],
       [7, 5, 7, 2, 2, 9],
       [1, 7, 8, 6, 9, 1],
       [1, 3, 1, 7, 6, 3],
       [9, 7, 6, 8, 1, 5]], dtype=int32)

In [104]:
arr.T

array([[7, 7, 1, 1, 9],
       [5, 5, 7, 3, 7],
       [4, 7, 8, 1, 6],
       [9, 2, 6, 7, 8],
       [8, 2, 9, 6, 1],
       [8, 9, 1, 3, 5]], dtype=int32)