In [3]:
# Numpy >> Numerical pyton >> 2005 by travis oliphant
# before 2005 there were special mathematic tools(similar to tara , Linga)

In [4]:
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
np.__version__

NameError: name 'np' is not defined

In [ ]:
print(np.__doc__)

In [ ]:
lis=[1,2,4,"Pwskills",2+5j,True,1.2] # list stores hetrogenous data
type(lis)

In [ ]:
# Numpy stores the data in numpy array
# An array is a container/data structure used to store data of same type>> Homogenous data

In [ ]:
# Why numpy? already we have list >> C is one of the most fastest programing langauge after c++
# numpy is built using c>>Numpy computation is fast
# Due to array >> Since it stores only homogenous data,numpy array is faster
# Since it stores homogenous data >> contiguous memory 

In [ ]:
l=[1,2,3,4,5]# Numpy array is homogenous >> all elements can be integers string ,float it can be anything

In [ ]:
np.array(l)

In [ ]:
arr=np.array(l)
type(arr)# Numpy.ndarray>> n Dimensional array

In [9]:
l=[1,2,4,5,'Hello']
np.array(l)

array(['1', '2', '4', '5', 'Hello'], dtype='<U21')

In [10]:
l=[1,2,4,5, 6.1]
np.array(l)

array([1. , 2. , 4. , 5. , 6.1])

In [15]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [16]:
arr.ndim

1

In [17]:
arr1=np.array([[1,2,3],[2,3,4]])
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
arr1.ndim

2

In [2]:
import numpy as np
mat=np.matrix([1,2,3,4])# matrix is a specialised arra of 2 dimension

In [3]:
type(mat)

numpy.matrix

In [4]:
mat.ndim

2

In [5]:
mat

matrix([[1, 2, 3, 4]])

In [6]:
# TO understand the dimension see the no of opening/closing sqaure bracket
# matrix will always be 2 dimensional

In [8]:
# More ways to arrays
# 1]
l=[1,2,3,4]
np.asarray(l)# Initial function asarray to convert to an array ,np.array come after this

array([1, 2, 3, 4])

In [9]:
#2]
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [10]:
# asanyarray will convert the input to an ndarray,but pass ndarray subclass throws
# if something is already an array or part of array, it will simply allow to pass through it

In [11]:
#example: we have
mat


matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [13]:
t=([1,2,3,4],[4,5,6,7])
type(t)

tuple

In [14]:
np.array(t)

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [21]:
# Accessing the elements of array
arr=np.array([1,2,3,4])
arr[0]

np.int64(1)

In [22]:
#array is mutable
arr[0]=1000
arr

array([1000,    2,    3,    4])

In [23]:
# a and arr will point to same memory location >> if we make changes in a it will affect arr also
a=arr

In [24]:
a

array([1000,    2,    3,    4])

In [25]:
arr

array([1000,    2,    3,    4])

In [26]:
# Shallow copy >> Change in one array will lead to change in another

In [27]:
a[0]=500
a

array([500,   2,   3,   4])

In [28]:
arr

array([500,   2,   3,   4])

In [33]:
#deep Copy >> Changses done in b is will not affect the original array
b=arr.copy()

In [34]:
b

array([500,   2,   3,   4])

In [35]:
b[0]=100
b

array([100,   2,   3,   4])

In [36]:
arr

array([500,   2,   3,   4])

In [38]:
#To create an array >> np.array ,np.asanyarray, np.asany

In [45]:
#Multiple approcehes to generate any array 

arr1=np.fromfunction(lambda i,j: i==j,(3,3))# Construct an array by executing a function over each coordinate

In [46]:
arr1

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [47]:
arr1.ndim

2

In [48]:
arr1.shape

(3, 3)

In [50]:
arr1.size# no of elements in array/

9

In [ ]:
# true is stored as 1 and false is stored as 0

In [51]:
np.fromfunction(lambda i,j: i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [52]:
for i in range (5):
    print(i)

0
1
2
3
4


In [53]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [54]:
iterator=(i for i in range(5))

In [56]:
iterator

<generator object <genexpr> at 0x00000272F7F08450>

In [57]:
np.fromiter(iterator,int)#Create a new 1-dimensional array from an iterable object

array([0, 1, 2, 3, 4])

In [64]:
np.fromstring("22 23 24",sep=" ",dtype=int )#A new 1-D array initialized from text data in a string.
#By default the dtype is float


array([22, 23, 24])

In [65]:
np.fromstring("22 23 24",sep=" " )

array([22., 23., 24.])

In [67]:
# for string character you have to use split 
string ="hello,how,are,you"
string.split(",")

['hello', 'how', 'are', 'you']

In [68]:
np.array(string.split(","))

array(['hello', 'how', 'are', 'you'], dtype='<U5')

In [69]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [70]:
range(10)

range(0, 10)

In [73]:
#other method of numpy >> TO generate a sequence of number
np.arange(1,10)# arrange returns evenly spacified value within a given interval



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.arange(1,10,0.1)# give number from 1 to 10 with step of 0.1

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [75]:
np.linspace(1,5,10)#give me 10 number between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])